# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: Boogie.Ben@outlook.com
author_name: BoogieBen
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_cpw
project_short_description: A JupyterLab extension. Enable Canvas Pipeline Workflow.
python_name: jupyterlab_cpw
repository: https://github.com/boogie-ben/jupyterlab-cpw
test: false

